name: Build and Test

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build_and_test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        docker: [opensuse/tumbleweed, opensuse/leap, 'fedora:33']
        pkg: [dnf]
        include:
          - docker: opensuse/tumbleweed
            pkg: zypper
          - docker: opensuse/leap
            pkg: zypper

    container: ${{ matrix.docker }}

    steps:
      - run: zypper -n install dnf
        if: ${{ startsWith(matrix.docker,  'opensuse') }}
      - run: cp -r /etc/zypp/repos.d /etc/dnf/
        if: ${{ startsWith(matrix.docker,  'opensuse') && matrix.pkg == 'dnf' }}
      - run: dnf search --refresh bzip2
        if: ${{ startsWith(matrix.docker,  'opensuse') && matrix.pkg == 'dnf'}}
      - run: dnf -y install --downloadonly
              checkbashisms cpio dash gzip
              bzip2 xz
              binutils glibc glibc-32bit glibc-locale desktop-file-utils
              appstream-glib
              myspell-en_US myspell-cs_CZ
              python3-magic
              python3-pyenchant
              python3-rpm
              python3-base
              python3-setuptools
              python3-pybeam
              python3-pytest
              python3-pytest-cov
              python3-pytest-flake8
              python3-pytest-xdist
              python3-flake8
              python3-flake8-builtins
              python3-flake8-bugbear
              python3-flake8-import-order
              python3-flake8-quotes
              python3-pyxdg
              python3-zstd
              python3-toml
              rpm-build
        if: ${{ startsWith(matrix.docker,  'opensuse') && matrix.pkg == 'dnf'}}
      - run: dnf -y install
              checkbashisms cpio dash gzip
              bzip2 xz
              binutils glibc glibc-32bit glibc-locale desktop-file-utils
              appstream-glib
              myspell-en_US myspell-cs_CZ
              python3-magic
              python3-pyenchant
              python3-rpm
              python3-base
              python3-setuptools
              python3-pybeam
              python3-pytest
              python3-pytest-cov
              python3-pytest-flake8
              python3-pytest-xdist
              python3-flake8
              python3-flake8-builtins
              python3-flake8-bugbear
              python3-flake8-import-order
              python3-flake8-quotes
              python3-pyxdg
              python3-zstd
              python3-toml
              rpm-build
        if: ${{ startsWith(matrix.docker,  'opensuse') && matrix.pkg == 'dnf'}}
      - run: zypper refresh
        if: ${{ startsWith(matrix.docker,  'opensuse') && matrix.pkg == 'dnf'}}
      - run: zypper -n install --download-only
              checkbashisms cpio dash gzip
              bzip2 xz
              binutils glibc glibc-32bit glibc-locale desktop-file-utils
              appstream-glib
              myspell-en_US myspell-cs_CZ
              python3-magic
              python3-pyenchant
              python3-rpm
              python3-base
              python3-setuptools
              python3-pybeam
              python3-pytest
              python3-pytest-cov
              python3-pytest-flake8
              python3-pytest-xdist
              python3-flake8
              python3-flake8-builtins
              python3-flake8-bugbear
              python3-flake8-import-order
              python3-flake8-quotes
              python3-pyxdg
              python3-zstd
              python3-toml
              rpm-build
        if: ${{ startsWith(matrix.docker,  'opensuse') && matrix.pkg == 'zypper'}}
      - run: zypper -n install
              checkbashisms cpio dash gzip
              bzip2 xz
              binutils glibc glibc-32bit glibc-locale desktop-file-utils
              appstream-glib
              myspell-en_US myspell-cs_CZ
              python3-magic
              python3-pyenchant
              python3-rpm
              python3-base
              python3-setuptools
              python3-pybeam
              python3-pytest
              python3-pytest-cov
              python3-pytest-flake8
              python3-pytest-xdist
              python3-flake8
              python3-flake8-builtins
              python3-flake8-bugbear
              python3-flake8-import-order
              python3-flake8-quotes
              python3-pyxdg
              python3-zstd
              python3-toml
              rpm-build
        if: ${{ startsWith(matrix.docker,  'opensuse') && matrix.pkg == 'zypper'}}
      - run: dnf search --refresh bzip2
        if: ${{ matrix.docker == 'fedora:33' }}
      - run: dnf --nogpgcheck -y install --downloadonly
              /usr/bin/appstream-util
              /usr/bin/cpio
              /usr/bin/bzip2
              /usr/bin/desktop-file-validate
              /usr/bin/python3
              /usr/bin/readelf
              /usr/bin/ldd
              /usr/bin/c++filt
              /usr/bin/xz
              dash
              devscripts-checkbashisms
              glibc
              glibc.i686
              hunspell-en
              hunspell-cs
              python3-setuptools
              python3-enchant
              python3-magic
              python3-rpm
              python3-pybeam
              python3-pytest
              python3-pytest-cov
              python3-pytest-flake8
              python3-pytest-xdist
              python3-flake8
              python3-flake8-import-order
              python3-pyxdg
              python3-toml
              python3-zstd
              rpm-build
        if: ${{ matrix.docker == 'fedora:33' }}
      - run: dnf --nogpgcheck -y install
              /usr/bin/appstream-util
              /usr/bin/cpio
              /usr/bin/bzip2
              /usr/bin/desktop-file-validate
              /usr/bin/python3
              /usr/bin/readelf
              /usr/bin/ldd
              /usr/bin/c++filt
              /usr/bin/xz
              dash
              devscripts-checkbashisms
              glibc
              glibc.i686
              hunspell-en
              hunspell-cs
              python3-setuptools
              python3-enchant
              python3-magic
              python3-rpm
              python3-pybeam
              python3-pytest
              python3-pytest-cov
              python3-pytest-flake8
              python3-pytest-xdist
              python3-flake8
              python3-flake8-import-order
              python3-pyxdg
              python3-toml
              python3-zstd
              rpm-build
        if: ${{ matrix.docker == 'fedora:33' }}
